import { ToolDefinition, ToolCategoryInfo, ToolCategory } from '../../types/tools';

export const TOOL_CATEGORIES: ToolCategoryInfo[] = [
  {
    id: 'OBSERVE',
    label: 'Observe',
    tagline: 'Real-time situational awareness & spatial telemetry',
    description: 'Direct measurement streams, hyper-local spatial sensing, and thermal footprint mapping.',
    iconName: 'Eye',
    colorClass: 'text-blue-600',
    bgLightClass: 'bg-blue-50',
    borderClass: 'border-blue-200',
    toolsCount: 4,
  },
  {
    id: 'ANALYZE',
    label: 'Analyze',
    tagline: 'Biophysical indices, change models & anomaly engines',
    description: 'Synthesized multidimensional pulse, thermal stress indices, and grounded environmental reasoning.',
    iconName: 'Activity',
    colorClass: 'text-emerald-600',
    bgLightClass: 'bg-emerald-50',
    borderClass: 'border-emerald-200',
    toolsCount: 5,
  },
  {
    id: 'PREDICT',
    label: 'Predict',
    tagline: 'Forward projections, peak detection & scenario labs',
    description: 'Diurnal curve modeling, high-risk window identification, and what-if simulation.',
    iconName: 'TrendingUp',
    colorClass: 'text-amber-600',
    bgLightClass: 'bg-amber-50',
    borderClass: 'border-amber-200',
    toolsCount: 5,
  },
  {
    id: 'MONITOR',
    label: 'Monitor',
    tagline: 'Custom spatial triggers, threshold watchdogs & alerts',
    description: 'User-defined automated surveillance, persistent monitors, and signal limits.',
    iconName: 'Radio',
    colorClass: 'text-cyan-600',
    bgLightClass: 'bg-cyan-50',
    borderClass: 'border-cyan-200',
    toolsCount: 4,
  },
  {
    id: 'ACT',
    label: 'Act',
    tagline: 'Action timelines, adaptive protocols & mitigation plans',
    description: 'Operational schedules, heat mitigation plans, and structured risk response protocols.',
    iconName: 'CheckSquare',
    colorClass: 'text-rose-600',
    bgLightClass: 'bg-rose-50',
    borderClass: 'border-rose-200',
    toolsCount: 4,
  },
  {
    id: 'EXPLORE',
    label: 'Explore',
    tagline: 'Cross-city benchmarks, historical timelines & spatial maps',
    description: 'Side-by-side comparative matrices, time retrospectives, and spatial exploration.',
    iconName: 'Compass',
    colorClass: 'text-sky-600',
    bgLightClass: 'bg-sky-50',
    borderClass: 'border-sky-200',
    toolsCount: 5,
  },
  {
    id: 'BUSINESS',
    label: 'Business',
    tagline: 'Asset monitoring, portfolios & executive reporting',
    description: 'Site resilience monitoring, multi-location portfolio risk matrices, and operational environmental briefs.',
    iconName: 'Building2',
    colorClass: 'text-purple-600',
    bgLightClass: 'bg-purple-50',
    borderClass: 'border-purple-200',
    toolsCount: 7,
  },
];

export const TOOLS_LIST: ToolDefinition[] = [
  // 1. OBSERVE
  {
    id: 'environmental-scan',
    name: 'Environmental Scan',
    category: 'OBSERVE',
    description: 'Instant multi-sensor scan answering "What is happening around this location?" with normalized telemetry.',
    iconName: 'Radar',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    contextualSource: 'Dashboard',
    tags: ['Live Scan', 'Telemetry', 'Multi-sensor', 'Surface Heat'],
  },
  {
    id: 'live-environment',
    name: 'Live Environment',
    category: 'OBSERVE',
    description: 'Continuous real-time stream of ambient temperature, FortyGuard surface anomalies, AQI, and humidity.',
    iconName: 'Activity',
    availability: 'LIVE',
    tier: 'FREE',
    tags: ['Real-Time', 'FortyGuard Mesh', 'Stream', 'Biophysical'],
  },
  {
    id: 'location-snapshot',
    name: 'Location Snapshot',
    category: 'OBSERVE',
    description: 'Comprehensive environmental profile, climate zone classification, thermal comfort index, and sensor footprint.',
    iconName: 'MapPin',
    availability: 'ACTIVE',
    tier: 'FREE',
    contextualSource: 'Navigation',
    tags: ['Profile', 'Microclimate', 'Zoning', 'Footprint'],
  },
  {
    id: 'satellite-spectroscopy',
    name: 'Satellite Spectroscopy',
    category: 'OBSERVE',
    description: 'Multi-spectral satellite reflectance imagery extracting hyper-local albedo, NDVI, and thermal emissivity indices.',
    iconName: 'Layers',
    availability: 'COMING SOON',
    tier: 'COMMERCIAL',
    tags: ['Albedo', 'NDVI', 'Emissivity', 'Multi-spectral'],
  },

  // 2. ANALYZE
  {
    id: 'heat-risk-analyzer',
    name: 'Heat Risk Analyzer',
    category: 'ANALYZE',
    description: 'Deterministic thermal stress evaluation combining ambient air, wet-bulb temperature, UHI delta, and solar radiation.',
    iconName: 'ShieldAlert',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    contextualSource: 'Weather',
    tags: ['Thermal Stress', 'Wet Bulb', 'UHI', 'Vulnerability'],
  },
  {
    id: 'environmental-pulse',
    name: 'Environmental Pulse',
    category: 'ANALYZE',
    description: 'Six-dimension biophysical composite scoring across Heat, Air, Water, Nature, Fire, and Solar stability.',
    iconName: 'Activity',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Pulse', 'Composite Score', '6 Dimensions', 'Resilience'],
  },
  {
    id: 'air-quality-analysis',
    name: 'Air Quality Analysis',
    category: 'ANALYZE',
    description: 'Ground-truth particulate (PM2.5/PM10), photochemical ozone (O3), NO2, and atmospheric ventilation audit.',
    iconName: 'Wind',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['AQI', 'PM2.5', 'Ozone', 'Atmospheric'],
  },
  {
    id: 'thermal-anomaly-analysis',
    name: 'Thermal Anomaly Analysis',
    category: 'ANALYZE',
    description: 'Statistical anomaly detection evaluating surface pavement radiative heat excess against regional baselines.',
    iconName: 'Flame',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Surface Anomaly', 'Urban Heat Island', 'Radiance', 'Mesh Delta'],
  },
  {
    id: 'grounded-research-assistant',
    name: 'Research Assistant',
    category: 'ANALYZE',
    description: 'AI-grounded microclimatic research assistant trained on biophysical meteorology and urban heat island physics.',
    iconName: 'Sparkles',
    availability: 'COMING SOON',
    tier: 'COMMERCIAL',
    tags: ['AI Agent', 'Scientific Literature', 'Biophysical AI'],
  },

  // 3. PREDICT
  {
    id: 'forecast-analyzer',
    name: 'Forecast Analyzer',
    category: 'PREDICT',
    description: 'Synoptic 24h & 5-day environmental forecasting with confidence degradation and diurnal curve modeling.',
    iconName: 'CloudSun',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Forecast', 'Diurnal Curve', 'Synoptic', 'Confidence'],
  },
  {
    id: 'environmental-trend',
    name: 'Environmental Trend',
    category: 'PREDICT',
    description: 'Multi-parameter rate of change and trajectory tracking across heat accumulation, AQI shifts, and humidity.',
    iconName: 'TrendingUp',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Trajectory', 'Rate of Change', 'Trend', 'Evolution'],
  },
  {
    id: 'scenario-explorer',
    name: 'Scenario Explorer',
    category: 'PREDICT',
    description: 'Simulate what-if parameters for severe heatwaves, canopy loss, humidity spikes, and urban cooling interventions.',
    iconName: 'FlaskConical',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Simulation', 'What-If', 'Canopy Loss', 'Cooling Modeling'],
  },
  {
    id: 'future-risk',
    name: 'Future Risk',
    category: 'PREDICT',
    description: 'Identify forward critical exposure windows for peak heat stress, intense UV irradiance, and trapped heat loads.',
    iconName: 'ShieldAlert',
    availability: 'ACTIVE',
    tier: 'FREE',
    isFeatured: true,
    contextualSource: 'Forecast',
    tags: ['Peak Exposure', 'Exposure Windows', 'UV Danger', '24h Horizon'],
  },
  {
    id: 'seasonal-teleconnection-lab',
    name: 'Seasonal Teleconnection Lab',
    category: 'PREDICT',
    description: 'Multi-month seasonal outlook utilizing El Niño Southern Oscillation (ENSO) and Pacific Decadal Oscillation indicators.',
    iconName: 'History',
    availability: 'COMING SOON',
    tier: 'ULTIMATE',
    tags: ['ENSO Outlook', 'Seasonal Modeling', 'Decadal Drift'],
  },

  // 4. MONITOR
  {
    id: 'create-monitor',
    name: 'Create Monitor',
    category: 'MONITOR',
    description: 'Define custom spatial triggers, anomaly alarms, condition thresholds, and multi-channel notification preferences.',
    iconName: 'BellPlus',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Custom Alert', 'Threshold Trigger', 'Duration', 'Proactive'],
  },
  {
    id: 'saved-monitors',
    name: 'Saved Monitors',
    category: 'MONITOR',
    description: 'Review, manage, pause, and calibrate all active persistent spatial monitors running in your surveillance network.',
    iconName: 'Radio',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Surveillance', 'Active Rules', 'Watchlist', 'Manage'],
  },
  {
    id: 'threshold-builder',
    name: 'Threshold Builder',
    category: 'MONITOR',
    description: 'Calibrate environmental sensitivity limits and multi-parameter trigger thresholds across heat, AQI, and UV.',
    iconName: 'Sliders',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Calibration', 'Sensitivity Limits', 'Triggers', 'Tolerance'],
  },
  {
    id: 'sensor-gateway-hub',
    name: 'Sensor Gateway Hub',
    category: 'MONITOR',
    description: 'Enterprise LoRaWAN and MQTT edge hardware integration bridge for private IoT weather stations and HVAC sensors.',
    iconName: 'Zap',
    availability: 'COMING SOON',
    tier: 'COMMERCIAL',
    tags: ['IoT Gateway', 'MQTT', 'LoRaWAN', 'Hardware Ingestion'],
  },

  // 5. ACT
  {
    id: 'heat-action-plan',
    name: 'Heat Action Plan',
    category: 'ACT',
    description: 'Chronological diurnal schedule with actionable operational milestones from morning prep to peak mitigation.',
    iconName: 'Clock',
    availability: 'ACTIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Timeline', 'Diurnal Schedule', 'OSHA Protocol', 'Operations'],
  },
  {
    id: 'risk-response-planner',
    name: 'Risk Response Planner',
    category: 'ACT',
    description: 'Structured mitigation protocols tailored to live conditions, municipal guidelines, and vulnerable assets.',
    iconName: 'CheckSquare',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Protocols', 'Response Action', 'Asset Defense', 'Checklists'],
  },
  {
    id: 'mitigation-recommendations',
    name: 'Mitigation Recommendations',
    category: 'ACT',
    description: 'Targeted cooling strategies including cool pavements, reflective roofs, misting pavilions, and urban forestry.',
    iconName: 'Trees',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Cool Roofs', 'Urban Forestry', 'Misting', 'Surface Cooling'],
  },
  {
    id: 'automated-iot-actuator',
    name: 'Automated IoT Actuator',
    category: 'ACT',
    description: 'Closed-loop BMS automation triggering misting systems, shade canopies, and HVAC economizers on heat threshold breaches.',
    iconName: 'Zap',
    availability: 'COMING SOON',
    tier: 'ULTIMATE',
    tags: ['BMS Automation', 'Closed-Loop', 'Misting Actuators', 'HVAC'],
  },

  // 6. EXPLORE
  {
    id: 'compare-locations',
    name: 'Compare Locations',
    category: 'EXPLORE',
    description: 'Side-by-side comparative matrix across up to 3 cities for heat risk, environmental pulse, AQI, and tree canopy.',
    iconName: 'SplitSquareVertical',
    availability: 'ACTIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Benchmark', 'Side-by-Side', 'Cross-City', 'Multi-city'],
  },
  {
    id: 'environmental-time-machine',
    name: 'Environmental Time Machine',
    category: 'EXPLORE',
    description: 'Retrospective timeline analyzing baseline deviations, historical temperature extremes, and seasonal drift.',
    iconName: 'History',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Historical', 'Retrospective', 'Seasonal Drift', 'Time-Series'],
  },
  {
    id: 'living-map',
    name: 'Living Map',
    category: 'EXPLORE',
    description: 'Spatial environmental intelligence map featuring thermal anomaly meshes, air dispersion, and pulse layers.',
    iconName: 'Compass',
    availability: 'LIVE',
    tier: 'FREE',
    tags: ['Spatial Grid', 'Map Layers', 'FortyGuard Mesh', 'Navigation'],
  },
  {
    id: 'cool-route-navigation',
    name: 'CoolRoute Navigation',
    category: 'EXPLORE',
    description: 'Thermal-optimized pedestrian routing minimizing urban heat island exposure and UV load using FortyGuard data.',
    iconName: 'Map',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Routing', 'Thermal Path', 'Navigation', 'UV Shield'],
  },
  {
    id: 'urban-heat-sandbox',
    name: 'Urban Heat Sandbox',
    category: 'EXPLORE',
    description: 'Interactive mitigation simulator. Place tree canopies and cool roofs to dynamically reduce UHI and calculate cooling impact.',
    iconName: 'MapPin',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Simulation', 'City Planning', 'Mitigation', 'Cool Roofs'],
  },
  {
    id: 'vulnerability-alert-system',
    name: 'Vulnerability Alert System',
    category: 'MONITOR',
    description: 'Overlay demographic and infrastructure data with thermal anomalies to protect schools, elderly care, and outdoor workers.',
    iconName: 'ShieldAlert',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Public Health', 'Demographics', 'Schools', 'OSHA'],
  },
  {
    id: 'regional-explorer',
    name: 'Regional Explorer',
    category: 'EXPLORE',
    description: 'Macro-scale state and multi-basin regional synoptic climate dynamics and atmospheric river tracking.',
    iconName: 'Maximize2',
    availability: 'COMING SOON',
    tier: 'FREE',
    tags: ['Regional', 'Macro Climate', 'Watershed', 'Synoptic'],
  },
  {
    id: 'data-lake-explorer',
    name: 'Data Lake Explorer',
    category: 'EXPLORE',
    description: 'Direct SQL & Parquet telemetry query interface for raw unaggregated NOAA, NASA, and FortyGuard spatial datasets.',
    iconName: 'Database',
    availability: 'COMING SOON',
    tier: 'COMMERCIAL',
    tags: ['Data Lake', 'Parquet Query', 'Spatial SQL', 'Raw Records'],
  },

  // 7. BUSINESS
  {
    id: 'my-sites',
    name: 'My Sites',
    category: 'BUSINESS',
    description: 'Centralized management of monitored facilities, campuses, and assets with pulse scores, temperature, and sync telemetry.',
    iconName: 'Building2',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Facility Management', 'Asset Telemetry', 'Campus Locations', 'Sync'],
  },
  {
    id: 'site-monitor',
    name: 'Site Monitor',
    category: 'BUSINESS',
    description: 'Rule-based watchdog surveillance across 6 environmental risk vectors (Heat anomaly, AQI, Extreme temp, Wind, Rain, Risk).',
    iconName: 'Building',
    availability: 'LIVE',
    tier: 'FREE',
    tags: ['Watchdogs', 'Rule Engine', 'Thresholds', 'Action Protocols'],
  },
  {
    id: 'portfolio-monitor',
    name: 'Portfolio View',
    category: 'BUSINESS',
    description: 'Multi-site risk matrix displaying 12 monitored commercial locations in compact grid/list format with active alert counts.',
    iconName: 'Layers',
    availability: 'LIVE',
    tier: 'FREE',
    isFeatured: true,
    tags: ['Enterprise', 'Multi-Site', '12 Locations', 'Risk Matrix'],
  },
  {
    id: 'environmental-brief',
    name: 'Environmental Brief',
    category: 'BUSINESS',
    description: 'Concise operational report synthesizing Current conditions, Key changes, Risks, Forecast, Alerts, and Recommended actions.',
    iconName: 'FileText',
    availability: 'LIVE',
    tier: 'FREE',
    tags: ['Executive Brief', '6 Sections', 'Operational Report', 'Compliance'],
  },
  {
    id: 'risk-report',
    name: 'Risk Report',
    category: 'BUSINESS',
    description: 'TCFD and ESG-aligned physical climate resilience audit quantifying financial exposure and heat risk.',
    iconName: 'ShieldAlert',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['ESG Climate', 'Physical Risk', 'TCFD', 'Audit'],
  },
  {
    id: 'operational-insights',
    name: 'Operational Insights',
    category: 'BUSINESS',
    description: 'Executive decision summary featuring "3 Things to Know" and priority high-leverage mitigation recommendations.',
    iconName: 'Sparkles',
    availability: 'ACTIVE',
    tier: 'FREE',
    tags: ['Executive Summary', '3 Things', 'Decisions', 'Operations'],
  },
  {
    id: 'scope-carbon-accounting',
    name: 'Scope Carbon Accounting',
    category: 'BUSINESS',
    description: 'Thermal-driven HVAC energy surge and indirect Scope 2 carbon emissions modeling for building operations.',
    iconName: 'TrendingUp',
    availability: 'COMING SOON',
    tier: 'COMMERCIAL',
    tags: ['Scope 2', 'HVAC Energy Surge', 'Emissions Accounting', 'ESG'],
  },
];
